data <- read.table("./household_power_consumption.txt", header=TRUE, sep = ";", na.strings="?")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
data <- subset(data,Date>="2007-02-01" & Date <="2007-02-02")

data$Global_active_power <- as.numeric(data$Global_active_power)
data$x <- paste(data$Date,data$Time)
data$x <- strptime(data$x,"%Y-%m-%d %H:%M:%S")
plot(x=data$x, y=data$Global_active_power, type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()
